### ISSUE TITLE
directive

### ISSUE THREAD

**Issue by wormen** [teropa/angular-virtual-dom#12]
tell me how to connect the user directive to your plug-in, or vice versa .... in general so that they can work together

**Comment by teropa** [comment]
For a directive to work within a `v-root`, it needs to have a `linkVirtual` function. The function receives a virtual DOM node object as an argument. There will be an extra `$scope` attribute on that object, holding the current scope. The function should do whatever processing it does, and return the resulting, modified virtual DOM node or a collection of them.

This is how it works currently, but I'm not happy with that API and it's likely to change.
